//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazaUrunTakipSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SATISLAR
    {
        public int id { get; set; }
        public Nullable<int> urun { get; set; }
        public Nullable<int> personal { get; set; }
        public Nullable<int> musteri { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual TBL_MUSTERI TBL_MUSTERI { get; set; }
        public virtual TBL_PERSONAL TBL_PERSONAL { get; set; }
        public virtual TBL_URUN TBL_URUN { get; set; }
    }
}
